---
# Note:
# First, replace "{{nfs-server-ip-address}}"
# by running this command:
# $ kubectl describe pod nfs-server | grep IP:
#
# Tried to reference nfs-server ip using kube-dns,
# but it did not work...
#     server: nfs-server.default.svc.cluster.local
#
# PersistentVolumes don't use namespaces.
# However, nfs runs in a container (with a namespace).
# So, a separate PersistentVolume is necessary to point to
# the nfs ip address in the autostructure-development namespace.
# The PersistentVolumeClaim wont care which volume it connects to,
# as long as the volume satisfies the claim (e.g. does it have the space?)
# added storageClassName: nfs-storage
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-vol-default
  labels:
    type: nfs
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.96.49.164
    path: /
