---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: nfs-claim-1g
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: "nfs"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: autostructure-development
  name: nfs-claim-3g
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      type: "nfs"
