---
# Deploying separate nfs-server nodes for each project and/or environment...
# Using a node selector to assign nfs to specific nodes (via the nfs-server role)
# e.g.
# kubectl label node nfs001 node-role.kubernetes.io/nfs-server=nfs-server
#
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nfs-server
  labels:
    role: nfs-server
spec:
  tolerations:
  - key: node-role.kubernetes.io/nfs-server
    effect: NoSchedule
  restartPolicy: Always
  volumes:
  - name: export-volume
    hostPath:
      path: /tmp/nfs-provisioner
  containers:
  - name: nfs-server
    image: quay.io/kubernetes_incubator/nfs-provisioner
    # image: gcr.io/google_containers/volume-nfs:0.8
    securityContext:
      privileged: true
    ports:
      - name: nfs-0
        containerPort: 2049
        protocol: TCP
    volumeMounts:
      - name: export-volume
        mountPath: /export
  nodeSelector:
    node-role.kubernetes.io/nfs-server: "nfs-server"
---
apiVersion: v1
kind: Pod
metadata:
  namespace: autostructure-development
  name: nfs-server
  labels:
    role: nfs-server
spec:
  tolerations:
  - key: node-role.kubernetes.io/nfs-server
    effect: NoSchedule
  restartPolicy: Always
  containers:
  - name: nfs-server
    image: quay.io/kubernetes_incubator/nfs-provisioner
    # image: gcr.io/google_containers/volume-nfs:0.8
    securityContext:
      privileged: true
    ports:
      - name: nfs-0
        containerPort: 2049
        protocol: TCP
  nodeSelector:
    node-role.kubernetes.io/nfs-server: "nfs-server"
