---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: nfs-claim-1g
  annotations:
    volume.beta.kubernetes.io/storage-class: "autostructure.io/nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: autostructure-development
  name: nfs-claim-3g
  annotations:
    volume.beta.kubernetes.io/storage-class: "autostructure.io/nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
