---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: autostructure-development
  name: test-nginx-ingress
  labels:
    app: test-nginx-ingress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-nginx-ingress
  template:
    metadata:
      labels:
        app: test-nginx-ingress
    spec:
      volumes:
        - name: nginx-nfs-vol-001
          persistentVolumeClaim:
            claimName: nfs-claim-1g
      containers:
        - name: nginx
          image: nginx:1.15.4
          ports:
            - containerPort: 80
              name: nginx-port
          volumeMounts:
            - name: nginx-nfs-vol-001
              mountPath: /usr/share/nginx/html
