---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: RENAME_ME
  labels:
    type: LABEL_ME
spec:
  storageClassName: RENAME_TO_STORAGECLASS
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.65.68
    path: /
