---
# create an ingress-resource in both the
# default & autostructure-development namespaces.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ci-cd
  name: nginx-ingress-jenkins-test
  labels:
    app: jenkins3
    chart: jenkins-0.26.0
    component: jenkins3-jenkins-master
    heritage: Tiller
    release: jenkins3
spec:
  backend:
    serviceName: jenkins3
    servicePort: 8080
  rules:
  - host: jenkins.autostructure.io
    http:
      paths:
      - backend:
          serviceName: jenkins3
          servicePort: 8080
        path: /
        
