---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: test-centos
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
        - name: centos
          image: library/centos:latest
          restartPolicy: Never
          command: ["sleep","360"]
          # need continuous running process or the container will close.
          # command:
          #   - "sleep"
          #   - "360"
          # OR...
          # command: ["tailf"]
          # args: ["/dev/null"]
          # 
          # volumeMounts:
          #   - name: nginx-nfs-vol-001
          #     mountPath: /usr/share/nginx/html
      # volumes:
      #   - name: nginx-nfs-vol-002
      #     persistentVolumeClaim:
      #       claimName: nfs-claim-3g
