---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: default
  name: nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/nfs
reclaimPolicy: Retain
