---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol-001
  labels:
    type: local
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  hostPath:
    path: /tmp/nfs/nfs-vol-001
---
# add more volumes here...
