---
apiVersion: v1
kind: Pod
metadata:
  # namespace: autostructure-lab
  name: nfs-server
  labels:
    role: nfs-server
spec:
  tolerations:
  - key: node-role.kubernetes.io/nfs-server
    effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/nfs-server: "nfs-server"
  restartPolicy: Always
  containers:
  - name: nfs-server
    image: gcr.io/google_containers/volume-nfs:0.8
    securityContext:
      privileged: true
    ports:
      - name: nfs-0
        containerPort: 2049
        protocol: TCP
    # volumeMounts:
    #   - name: nfs-root-volume
    #     mountPath: /exports
  # volumes:
  #   - name: nfs-root-volume
  #     emptyDir: {}
