---
# PersistentVolumes don't use namespaces.
# However, nfs runs in a container (with a namespace).
# So, a separate PersistentVolume is necessary to point to
# the nfs ip address in the autostructure-development namespace.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol-autostructure-development
  labels:
    type: nfs
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.65.70
    path: /
