---
apiVersion: v1
kind: PersistentVolume
metadata:
  # namespace: autostructure-lab
  name: nfs-vol-001
  labels:
    type: nfs
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.65.68
    path: /
