---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-vol-001
  labels:
    type: nfs
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.65.68
    path: /
---
# add more volumes here...
